// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR8OlkV8mBiAUi1iag0WE0SOK-s7ET0FY',
    appId: '1:607082432922:web:b2d4de8ba9ddd1962e1223',
    messagingSenderId: '607082432922',
    projectId: 'flashcards-ai-efd18',
    authDomain: 'flashcards-ai-efd18.firebaseapp.com',
    storageBucket: 'flashcards-ai-efd18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXhhjmuIXk42heIJ22by2QEHUpETrY_M',
    appId: '1:607082432922:android:05a4b449a3cd55f62e1223',
    messagingSenderId: '607082432922',
    projectId: 'flashcards-ai-efd18',
    storageBucket: 'flashcards-ai-efd18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtV5NDQf-yc0NLLB32op7QSvwj7UmmAGw',
    appId: '1:607082432922:ios:d1e67a44bd74962d2e1223',
    messagingSenderId: '607082432922',
    projectId: 'flashcards-ai-efd18',
    storageBucket: 'flashcards-ai-efd18.firebasestorage.app',
    iosClientId:
        '607082432922-2ui57aatcbepdo922oaeg46knpmuqe6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardstfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtV5NDQf-yc0NLLB32op7QSvwj7UmmAGw',
    appId: '1:607082432922:ios:d1e67a44bd74962d2e1223',
    messagingSenderId: '607082432922',
    projectId: 'flashcards-ai-efd18',
    storageBucket: 'flashcards-ai-efd18.firebasestorage.app',
    iosClientId:
        '607082432922-2ui57aatcbepdo922oaeg46knpmuqe6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardstfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR8OlkV8mBiAUi1iag0WE0SOK-s7ET0FY',
    appId: '1:607082432922:web:0595f15969b3788a2e1223',
    messagingSenderId: '607082432922',
    projectId: 'flashcards-ai-efd18',
    authDomain: 'flashcards-ai-efd18.firebaseapp.com',
    storageBucket: 'flashcards-ai-efd18.firebasestorage.app',
  );
}
